// events
export const EVENT_ERROR = 'EVENT_ERROR';

export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const OPEN_POSITION = 'OPEN_POSITION';
export const CANDLE_CLOSED = 'CANDLE_CLOSED';

export const OPEN_AVERAGE_ORDER = 'OPEN_AVERAGE_ORDER';

// errors
export const ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND';
export const ERR_INVALID_PASSWORD = 'ERR_INVALID_PASSWORD';
export const NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
