// events
export const EVENT_ERROR = 'EVENT_ERROR';

export const SUBMIT_OPEN_ORDER = 'SUBMIT_OPEN_ORDER';
export const CANDLE_CLOSED = 'CANDLE_CLOSED';

export const SUBMIT_AVG_ORDER = 'SUBMIT_AVG_ORDER';
export const SUBMIT_PROFIT_ORDER = 'SUBMIT_PROFIT_ORDER';

export const ERROR_EVENT = 'ERROR_EVENT';
export const LOG_EVENT = 'LOG_EVENT';

// errors
export const ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND';
export const ERR_INVALID_PASSWORD = 'ERR_INVALID_PASSWORD';
export const NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
