// events
export const EVENT_ERROR = 'EVENT_ERROR';

export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const GET_LAST_KLINE_LOW_PRICE = 'GET_LAST_KLINE_LOW_PRICE';

// errors
export const ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND';
export const ERR_INVALID_PASSWORD = 'ERR_INVALID_PASSWORD';
