// REDIS SETTINGS KEYS

export const AVG_RATE = 'AVG_RATE';
export const CATEGORY = 'CATEGORY';
export const DIGITS = 'DIGITS';
export const MARTIN = 'MARTIN';
export const MAX_AVG_COUNT = 'MAX_AVG_COUNT';
export const MIN_CANDLES = 'MIN_CANDLES';
export const PERIOD = 'PERIOD';
export const PROFIT_RATE = 'PROFIT_RATE';
export const QUANTITY = 'QUANTITY';
export const SYMBOL = 'SYMBOL';
export const MAX_TRADES = 'MAX_TRADES';

// STORE KEYS

export const AVG_ORDER_COUNT = 'AVG_ORDER_COUNT';
export const AVG_ORDER_EXISTS = 'AVG_ORDER_EXISTS';
export const AVG_POS_PRICE = 'AVG_POS_PRICE';
export const LAST_AVG_ORDER_PRICE = 'LAST_AVG_ORDER_PRICE';
export const POS_QTY = 'POS_QTY';
export const POSITION_EXISTS = 'POSITION_EXISTS';
export const TRADES_COUNT = 'TRADES_COUNT';

// user keys

export const API_KEY = 'API_KEY';
export const API_SECRET = 'API_SECRET';
export const APP_STATUS = 'APP_STATUS';
export const UPDATED_AT = 'UPDATED_AT';
export const UPCOMING_ACTION = 'UPCOMING_ACTION';
export const AVERAGE_ORDER = 'AVERAGE_ORDER';
export const TAKE_PROFIT_ORDER = 'TAKE_PROFIT_ORDER';

// REDIS SETTINGS KEYS
export const REDIS_SETTINGS_KEYS = [
  AVG_RATE,
  CATEGORY,
  DIGITS,
  MARTIN,
  MAX_AVG_COUNT,
  MIN_CANDLES,
  PERIOD,
  PROFIT_RATE,
  QUANTITY,
  SYMBOL,
  MAX_TRADES,
];

// STORE KEYS
export const STORE_KEYS = [
  AVG_ORDER_COUNT,
  AVG_ORDER_EXISTS,
  AVG_POS_PRICE,
  LAST_AVG_ORDER_PRICE,
  POS_QTY,
  POSITION_EXISTS,
  TRADES_COUNT,
];
