name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Other steps like building or testing here
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/bybit/bybit-trader
          git pull origin main
          # Any other deployment commands
          # Navigate to the directory containing docker-compose.yml
          cd ~/bybit

          # Optionally, build and pull the latest versions of your containers
          # docker-compose build
          # docker-compose pull

          # Launch or update the Docker containers
          docker-compose up -d --no-deps --build bybit-bot-1 bybit-bot-2
          